#
#             MyUSB Library
#     Copyright (C) Dean Camera, 2008.
#              
#  dean [at] fourwalledcubicle [dot] com
#      www.fourwalledcubicle.com
#
# Released under the LGPL Licence, Version 3
#

# Makefile to build all the MyUSB Projects. Call with "make all" to
# rebuild all projects.

# Projects are pre-cleaned before each one is built, to ensure any
# custom MyUSB library build options are reflected in the compiled
# code.

all:
	make -C MagStripe clean
	make -C MagStripe all

clean:
	make -C MagStripe clean
	
clean_list:
	make -C MagStripe clean_list
