#
#             MyUSB Library
#     Copyright (C) Dean Camera, 2008.
#              
#  dean [at] fourwalledcubicle [dot] com
#      www.fourwalledcubicle.com
#
# Released under the GPL Licence, Version 3
#

# Makefile for the MyUSB bootloaders.

%:
	make -C 'DFU Class/' $@
	make -C 'CDC Class/' $@
