#
#             MyUSB Library
#     Copyright (C) Dean Camera, 2007.
#              
#  dean [at] fourwalledcubicle [dot] com
#      www.fourwalledcubicle.com
#
# Released under the GPL Licence, Version 3
#

# Makefile to build the MyUSB Demos. Call with "make all" to rebuild
# all demos.

%:
	make -C TestApp $@
	make -C Mouse $@
	make -C Keyboard $@
